services:
  - type: web
    name: silentsignal
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: OWNER_PASSWORD
        sync: false
    healthCheckPath: /
    autoDeploy: true
    staticPublishPath: ./ 