services:
  - type: web
    name: silent-signal
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    staticPublishPath: ./ 